### PR TITLE
run python thru `ruff check --fix --unsafe-fixes`

### PR DESCRIPTION
**Pull request by cooljeanius**
As with cooljeanius/apple-gdb-1824#79, I'm going to have to read up on `ruff`'s documentation to learn why it labels these particular fixes as "unsafe"...

### CODE REVIEW

**Comment by Elvish-Hunter** [comment]
I just randomly looked at one of the proposed changes, which is removing the `t_key=` and `t_val=` assignments from `wesnoth_pretty_printers.py`. This will end up in a disaster, because just three lines below there's this string interpolation:

    pair = "std::pair<%s const, %s>" % (t_key, t_val)

While changing things like `if x == None:` with `if x is None:` is safe, and the same goes for `True` and `False`, everything else must be checked carefully.

**Comment by CelticMinstrel** [comment]
All the `==` to `is` changes look fine. Everything else looks downright wrong – seems like it's just randomly removing assignments. In one case it even substitutes `variable = "string"` with just `"string"` which could never possibly be right.

**Comment by ProditorMagnus** [comment]
> I just randomly looked at one of the proposed changes, which is removing the `t_key=` and `t_val=` assignments from `wesnoth_pretty_printers.py`. This will end up in a disaster, because just three lines below there's this string interpolation:
> 
> ```
> pair = "std::pair<%s const, %s>" % (t_key, t_val)
> ```
> 
> While changing things like `if x == None:` with `if x is None:` is safe, and the same goes for `True` and `False`, everything else must be checked carefully.

You probably look wrong branch. Such line does not exist.

**Comment by ProditorMagnus** [comment]
> In one case it even substitutes `variable = "string"` with just `"string"` which could never possibly be right.

That is case of tool not being able to prove that statement has no side effects. Person would delete entire line.

**Comment by CelticMinstrel** [comment]
I don't know for sure that these changes are wrong. I only know they _look_ suspicious, because they're deleting assignments. You'll need to check that the assigned variables are truly unreferenced after being assigned. Also, in at least some cases, if you _can_ determine they're unreferenced, you'll want to delete the whole line instead of only the assignment.

**Comment by cooljeanius** [comment]
About the removed assignments: does python have a way to mark things as intentionally unused? I'm thinking about how in C, there are casts to `(void)`, and `__attribute__((used))` and `__attribute__((unused))`, and `#pragma unused`... anything similar I could use here instead of just removing the assignments?

**Comment by CelticMinstrel** [comment]
I don't know of any such thing, no.

**Comment by cooljeanius** [comment]
> I don't know of any such thing, no. Other than the convention of using `_` as the name of a variable when you don't intend to use it, but I think that doesn't apply here.

Well, I think I'll give it a try anyways to see if `ruff` (or any of the CI checks) will say anything about it; if it doesn't work, well, this is just a draft that I might not actually do anything with, so...

**Comment by CelticMinstrel** [comment]
Normally you'd only use `_` for a loop variable, or when unpacking a tuple, but whatever…

**Comment by cooljeanius** [comment]
So, even though this will make #148 more difficult, I think I'm going to merge this now anyways...

**Pull request merged**
